# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

before_install:
- openssl aes-256-cbc -K $encrypted_4000f4d8bf69_key -iv $encrypted_4000f4d8bf69_iv
  -in labdevopscloud-gabydias-7454ebb388ce.json.enc -out ../labdevopscloud-gabydias-7454ebb388ce.json
  -d

# Definir o Deploy no Heroku
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    edge: true 
    app: devopslab-gabylima
    on:
      branch: main

# Definir o Deploy no Google AppEngine
  - provider: gae
    keyfile: ../labdevopscloud-gabydias-7454ebb388ce.json
    project: labdevopscloud-gabydias
    on:
      branch: main
